name: Argo CD GitOps CI/CD

on:
  push:
    branches:
      - main
      - stg
    paths:
      - 'src/hello-world/**'

jobs:
  build:
    name: Build and Push the image
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./src/hello-world
          file: ./src/hello-world/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:${{ github.sha }}, ${{ secrets.DOCKERHUB_USERNAME }}/hello-world:latest

  update:
    name: Update Helm Manifests
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Update Image Tag Values
        if: github.ref == 'refs/heads/main' # Update values_prd.yaml on main branch
        run: |
          chart_dir="chart"
          new_image_tag=${{ github.sha }}
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values_prd.yaml"

      - name: Update Image Tag Values for Staging
        if: github.ref == 'refs/heads/stg' # Update values_stg.yaml on stg branch
        run: |
          chart_dir="chart"
          new_image_tag=${{ github.sha }}
          sed -i "s/^  tag: .*/  tag: $new_image_tag/" "$chart_dir/values_stg.yaml"

      - name: Commit the changes made
        run: | 
          git config --global user.name 'dgtvlz'
          git config --global user.email 'diegogtvz@gmail.com'
          git commit -am "updating image tag"
          git push
